# coding: utf-8

"""
    Machship API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.consignment_response_v2_i_collection_base_domain_entity_v2 import ConsignmentResponseV2ICollectionBaseDomainEntityV2  # noqa: E501
from swagger_client.rest import ApiException


class TestConsignmentResponseV2ICollectionBaseDomainEntityV2(unittest.TestCase):
    """ConsignmentResponseV2ICollectionBaseDomainEntityV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsignmentResponseV2ICollectionBaseDomainEntityV2(self):
        """Test ConsignmentResponseV2ICollectionBaseDomainEntityV2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.consignment_response_v2_i_collection_base_domain_entity_v2.ConsignmentResponseV2ICollectionBaseDomainEntityV2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
