# coding: utf-8

"""
    Machship API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.consignment_id_with_tracking_history_v2_i_enumerable_base_domain_entity import ConsignmentIdWithTrackingHistoryV2IEnumerableBaseDomainEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestConsignmentIdWithTrackingHistoryV2IEnumerableBaseDomainEntity(unittest.TestCase):
    """ConsignmentIdWithTrackingHistoryV2IEnumerableBaseDomainEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsignmentIdWithTrackingHistoryV2IEnumerableBaseDomainEntity(self):
        """Test ConsignmentIdWithTrackingHistoryV2IEnumerableBaseDomainEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.consignment_id_with_tracking_history_v2_i_enumerable_base_domain_entity.ConsignmentIdWithTrackingHistoryV2IEnumerableBaseDomainEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
