# coding: utf-8

"""
    Machship API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.company_v2 import CompanyV2  # noqa: E501
from swagger_client.rest import ApiException


class TestCompanyV2(unittest.TestCase):
    """CompanyV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompanyV2(self):
        """Test CompanyV2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.company_v2.CompanyV2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
