# coding: utf-8

"""
    Machship API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.consignments_api import ConsignmentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestConsignmentsApi(unittest.TestCase):
    """ConsignmentsApi unit test stubs"""

    def setUp(self):
        self.api = ConsignmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apiv2_consignments_create_consignment_post(self):
        """Test case for apiv2_consignments_create_consignment_post

        Creates an unmanifested consignment in Machship  # noqa: E501
        """
        pass

    def test_apiv2_consignments_create_consignmentwith_complex_items_post(self):
        """Test case for apiv2_consignments_create_consignmentwith_complex_items_post

        Creates an unmanifested consignment in Machship  # noqa: E501
        """
        pass

    def test_apiv2_consignments_create_existing_consignment_post(self):
        """Test case for apiv2_consignments_create_existing_consignment_post

        Creates an unmanifested consignment in Machship  # noqa: E501
        """
        pass

    def test_apiv2_consignments_delete_unmanifested_consignments_post(self):
        """Test case for apiv2_consignments_delete_unmanifested_consignments_post

        Deletes the specified Unmanifested Consignments in Machship  # noqa: E501
        """
        pass

    def test_apiv2_consignments_edit_unmanifested_consignment_post(self):
        """Test case for apiv2_consignments_edit_unmanifested_consignment_post

        Edit a consignment - note that it must be in an \"unmanifested\" state for this to be a valid operation  # noqa: E501
        """
        pass

    def test_apiv2_consignments_get_active_get(self):
        """Test case for apiv2_consignments_get_active_get

        Return all consignments for a company, regardless of status  # noqa: E501
        """
        pass

    def test_apiv2_consignments_get_all_get(self):
        """Test case for apiv2_consignments_get_all_get

        Return all consignments for a company, regardless of status  # noqa: E501
        """
        pass

    def test_apiv2_consignments_get_attachments_post(self):
        """Test case for apiv2_consignments_get_attachments_post

        Gets attachment information for a given consignment  # noqa: E501
        """
        pass

    def test_apiv2_consignments_get_completed_get(self):
        """Test case for apiv2_consignments_get_completed_get

        Returns consignments for the given company that were completed within the provided start and end date range. Limited to 2000 consignments at a time.  # noqa: E501
        """
        pass

    def test_apiv2_consignments_get_consignment_by_pending_consignment_id_get(self):
        """Test case for apiv2_consignments_get_consignment_by_pending_consignment_id_get

        Get a Consignment Details (if it exists) for a single consignment, using a pending consignment ID that  has been transformed (linked) into a consignment  # noqa: E501
        """
        pass

    def test_apiv2_consignments_get_consignment_for_clone_get(self):
        """Test case for apiv2_consignments_get_consignment_for_clone_get

        Get the details of an existing consignment in a format that can be passed to the createConsignmentWithComplexItems endpoint  # noqa: E501
        """
        pass

    def test_apiv2_consignments_get_consignment_get(self):
        """Test case for apiv2_consignments_get_consignment_get

        Get Consignment Details for a single consignment  # noqa: E501
        """
        pass

    def test_apiv2_consignments_get_recently_created_or_updated_consignments_get(self):
        """Test case for apiv2_consignments_get_recently_created_or_updated_consignments_get

        Return consignments for a company that have been created or updated within the timeframe specified  # noqa: E501
        """
        pass

    def test_apiv2_consignments_get_unmanifested_consignment_for_edit_get(self):
        """Test case for apiv2_consignments_get_unmanifested_consignment_for_edit_get

        Get an unmanifested consignment in the same format required to perform an update in the edit endpoint  # noqa: E501
        """
        pass

    def test_apiv2_consignments_get_unmanifested_get(self):
        """Test case for apiv2_consignments_get_unmanifested_get

        Get all consignments for a company that are in an \"unmanifested\" state  # noqa: E501
        """
        pass

    def test_apiv2_consignments_return_consignment_statuses_post(self):
        """Test case for apiv2_consignments_return_consignment_statuses_post

        Return all statuses recorded in the system with an option to specify a cutoff date to limit the statuses returned to ones saved in Machship  after a certain date. Maximum of 100 consignments  # noqa: E501
        """
        pass

    def test_apiv2_consignments_return_consignments_by_carrier_consignment_id_post(self):
        """Test case for apiv2_consignments_return_consignments_by_carrier_consignment_id_post

        Get Consignment Details for a multiple consignments using the Carrier Consignment ID as the lookup. Maximum of 10 consignments per request  # noqa: E501
        """
        pass

    def test_apiv2_consignments_return_consignments_by_pending_consignment_ids_post(self):
        """Test case for apiv2_consignments_return_consignments_by_pending_consignment_ids_post

        Get Consignment Details for multiple consignments using the Pending Consignment Id as the lookup. Maximum of 100 consignments.  # noqa: E501
        """
        pass

    def test_apiv2_consignments_return_consignments_by_reference1_post(self):
        """Test case for apiv2_consignments_return_consignments_by_reference1_post

        Get Consignment Details for a multiple consignments using Reference 1 as the lookup. Maximum of 10 consignments per request  # noqa: E501
        """
        pass

    def test_apiv2_consignments_return_consignments_by_reference2_post(self):
        """Test case for apiv2_consignments_return_consignments_by_reference2_post

        Get Consignment Details for a multiple consignments using Reference 2 as the lookup. Maximum of 10 consignments per request  # noqa: E501
        """
        pass

    def test_apiv2_consignments_return_consignments_post(self):
        """Test case for apiv2_consignments_return_consignments_post

        Get Consignment Details for a multiple consignments. Maximum of 100 consignments per request  # noqa: E501
        """
        pass

    def test_apiv2_consignments_search_consignments_post(self):
        """Test case for apiv2_consignments_search_consignments_post

        Get the details of related consignments based on the provided list of consignment or item references  # noqa: E501
        """
        pass

    def test_apiv2_consignments_update_consignment_statuses_post(self):
        """Test case for apiv2_consignments_update_consignment_statuses_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
