# coding: utf-8

"""
    Machship API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.carrier_invoice_entry_v2_for_get_entries_endpoint_i_collection_base_domain_entity_v2 import CarrierInvoiceEntryV2ForGetEntriesEndpointICollectionBaseDomainEntityV2  # noqa: E501
from swagger_client.rest import ApiException


class TestCarrierInvoiceEntryV2ForGetEntriesEndpointICollectionBaseDomainEntityV2(unittest.TestCase):
    """CarrierInvoiceEntryV2ForGetEntriesEndpointICollectionBaseDomainEntityV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCarrierInvoiceEntryV2ForGetEntriesEndpointICollectionBaseDomainEntityV2(self):
        """Test CarrierInvoiceEntryV2ForGetEntriesEndpointICollectionBaseDomainEntityV2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.carrier_invoice_entry_v2_for_get_entries_endpoint_i_collection_base_domain_entity_v2.CarrierInvoiceEntryV2ForGetEntriesEndpointICollectionBaseDomainEntityV2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
