# coding: utf-8

"""
    Machship API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_type import UserType  # noqa: E501
from swagger_client.rest import ApiException


class TestUserType(unittest.TestCase):
    """UserType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserType(self):
        """Test UserType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_type.UserType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
