# coding: utf-8

"""
    Machship API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.raw_pending_consignment_details_v2 import RawPendingConsignmentDetailsV2  # noqa: E501
from swagger_client.rest import ApiException


class TestRawPendingConsignmentDetailsV2(unittest.TestCase):
    """RawPendingConsignmentDetailsV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRawPendingConsignmentDetailsV2(self):
        """Test RawPendingConsignmentDetailsV2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.raw_pending_consignment_details_v2.RawPendingConsignmentDetailsV2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
