# coding: utf-8

"""
    Machship API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.identity_provider_v2_base_domain_entity_v2 import IdentityProviderV2BaseDomainEntityV2  # noqa: E501
from swagger_client.rest import ApiException


class TestIdentityProviderV2BaseDomainEntityV2(unittest.TestCase):
    """IdentityProviderV2BaseDomainEntityV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentityProviderV2BaseDomainEntityV2(self):
        """Test IdentityProviderV2BaseDomainEntityV2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.identity_provider_v2_base_domain_entity_v2.IdentityProviderV2BaseDomainEntityV2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
