# coding: utf-8

"""
    Machship API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.routing_no_lane_rates_type import RoutingNoLaneRatesType  # noqa: E501
from swagger_client.rest import ApiException


class TestRoutingNoLaneRatesType(unittest.TestCase):
    """RoutingNoLaneRatesType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoutingNoLaneRatesType(self):
        """Test RoutingNoLaneRatesType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.routing_no_lane_rates_type.RoutingNoLaneRatesType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
