# coding: utf-8

"""
    Machship API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CarrierInvoiceEntryInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'reason': 'str',
        'status': 'CarrierInvoiceEntryStatus',
        'consignment_id': 'int',
        'total': 'float'
    }

    attribute_map = {
        'id': 'id',
        'reason': 'reason',
        'status': 'status',
        'consignment_id': 'consignmentId',
        'total': 'total'
    }

    def __init__(self, id=None, reason=None, status=None, consignment_id=None, total=None):  # noqa: E501
        """CarrierInvoiceEntryInfo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._reason = None
        self._status = None
        self._consignment_id = None
        self._total = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if reason is not None:
            self.reason = reason
        if status is not None:
            self.status = status
        if consignment_id is not None:
            self.consignment_id = consignment_id
        if total is not None:
            self.total = total

    @property
    def id(self):
        """Gets the id of this CarrierInvoiceEntryInfo.  # noqa: E501


        :return: The id of this CarrierInvoiceEntryInfo.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CarrierInvoiceEntryInfo.


        :param id: The id of this CarrierInvoiceEntryInfo.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def reason(self):
        """Gets the reason of this CarrierInvoiceEntryInfo.  # noqa: E501


        :return: The reason of this CarrierInvoiceEntryInfo.  # noqa: E501
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this CarrierInvoiceEntryInfo.


        :param reason: The reason of this CarrierInvoiceEntryInfo.  # noqa: E501
        :type: str
        """

        self._reason = reason

    @property
    def status(self):
        """Gets the status of this CarrierInvoiceEntryInfo.  # noqa: E501


        :return: The status of this CarrierInvoiceEntryInfo.  # noqa: E501
        :rtype: CarrierInvoiceEntryStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this CarrierInvoiceEntryInfo.


        :param status: The status of this CarrierInvoiceEntryInfo.  # noqa: E501
        :type: CarrierInvoiceEntryStatus
        """

        self._status = status

    @property
    def consignment_id(self):
        """Gets the consignment_id of this CarrierInvoiceEntryInfo.  # noqa: E501


        :return: The consignment_id of this CarrierInvoiceEntryInfo.  # noqa: E501
        :rtype: int
        """
        return self._consignment_id

    @consignment_id.setter
    def consignment_id(self, consignment_id):
        """Sets the consignment_id of this CarrierInvoiceEntryInfo.


        :param consignment_id: The consignment_id of this CarrierInvoiceEntryInfo.  # noqa: E501
        :type: int
        """

        self._consignment_id = consignment_id

    @property
    def total(self):
        """Gets the total of this CarrierInvoiceEntryInfo.  # noqa: E501


        :return: The total of this CarrierInvoiceEntryInfo.  # noqa: E501
        :rtype: float
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this CarrierInvoiceEntryInfo.


        :param total: The total of this CarrierInvoiceEntryInfo.  # noqa: E501
        :type: float
        """

        self._total = total

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CarrierInvoiceEntryInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CarrierInvoiceEntryInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
