# coding: utf-8

"""
    Machship API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CarrierLiteWithCustomFieldSets(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'abbreviation': 'str',
        'display_name': 'str',
        'custom_field_sets': 'list[CustomFieldSet]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'abbreviation': 'abbreviation',
        'display_name': 'displayName',
        'custom_field_sets': 'customFieldSets'
    }

    def __init__(self, id=None, name=None, abbreviation=None, display_name=None, custom_field_sets=None):  # noqa: E501
        """CarrierLiteWithCustomFieldSets - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._abbreviation = None
        self._display_name = None
        self._custom_field_sets = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if abbreviation is not None:
            self.abbreviation = abbreviation
        if display_name is not None:
            self.display_name = display_name
        if custom_field_sets is not None:
            self.custom_field_sets = custom_field_sets

    @property
    def id(self):
        """Gets the id of this CarrierLiteWithCustomFieldSets.  # noqa: E501


        :return: The id of this CarrierLiteWithCustomFieldSets.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CarrierLiteWithCustomFieldSets.


        :param id: The id of this CarrierLiteWithCustomFieldSets.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this CarrierLiteWithCustomFieldSets.  # noqa: E501


        :return: The name of this CarrierLiteWithCustomFieldSets.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CarrierLiteWithCustomFieldSets.


        :param name: The name of this CarrierLiteWithCustomFieldSets.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def abbreviation(self):
        """Gets the abbreviation of this CarrierLiteWithCustomFieldSets.  # noqa: E501


        :return: The abbreviation of this CarrierLiteWithCustomFieldSets.  # noqa: E501
        :rtype: str
        """
        return self._abbreviation

    @abbreviation.setter
    def abbreviation(self, abbreviation):
        """Sets the abbreviation of this CarrierLiteWithCustomFieldSets.


        :param abbreviation: The abbreviation of this CarrierLiteWithCustomFieldSets.  # noqa: E501
        :type: str
        """

        self._abbreviation = abbreviation

    @property
    def display_name(self):
        """Gets the display_name of this CarrierLiteWithCustomFieldSets.  # noqa: E501


        :return: The display_name of this CarrierLiteWithCustomFieldSets.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this CarrierLiteWithCustomFieldSets.


        :param display_name: The display_name of this CarrierLiteWithCustomFieldSets.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def custom_field_sets(self):
        """Gets the custom_field_sets of this CarrierLiteWithCustomFieldSets.  # noqa: E501


        :return: The custom_field_sets of this CarrierLiteWithCustomFieldSets.  # noqa: E501
        :rtype: list[CustomFieldSet]
        """
        return self._custom_field_sets

    @custom_field_sets.setter
    def custom_field_sets(self, custom_field_sets):
        """Sets the custom_field_sets of this CarrierLiteWithCustomFieldSets.


        :param custom_field_sets: The custom_field_sets of this CarrierLiteWithCustomFieldSets.  # noqa: E501
        :type: list[CustomFieldSet]
        """

        self._custom_field_sets = custom_field_sets

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CarrierLiteWithCustomFieldSets, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CarrierLiteWithCustomFieldSets):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
