# coding: utf-8

"""
    Machship API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CarrierServiceSubService(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'carrier_service_id': 'int',
        'carrier_service': 'CarrierServiceLite',
        'sub_service_id': 'int',
        'sub_service': 'SubService',
        'is_default': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'carrier_service_id': 'carrierServiceId',
        'carrier_service': 'carrierService',
        'sub_service_id': 'subServiceId',
        'sub_service': 'subService',
        'is_default': 'isDefault'
    }

    def __init__(self, id=None, carrier_service_id=None, carrier_service=None, sub_service_id=None, sub_service=None, is_default=None):  # noqa: E501
        """CarrierServiceSubService - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._carrier_service_id = None
        self._carrier_service = None
        self._sub_service_id = None
        self._sub_service = None
        self._is_default = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if carrier_service_id is not None:
            self.carrier_service_id = carrier_service_id
        if carrier_service is not None:
            self.carrier_service = carrier_service
        if sub_service_id is not None:
            self.sub_service_id = sub_service_id
        if sub_service is not None:
            self.sub_service = sub_service
        if is_default is not None:
            self.is_default = is_default

    @property
    def id(self):
        """Gets the id of this CarrierServiceSubService.  # noqa: E501


        :return: The id of this CarrierServiceSubService.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CarrierServiceSubService.


        :param id: The id of this CarrierServiceSubService.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def carrier_service_id(self):
        """Gets the carrier_service_id of this CarrierServiceSubService.  # noqa: E501


        :return: The carrier_service_id of this CarrierServiceSubService.  # noqa: E501
        :rtype: int
        """
        return self._carrier_service_id

    @carrier_service_id.setter
    def carrier_service_id(self, carrier_service_id):
        """Sets the carrier_service_id of this CarrierServiceSubService.


        :param carrier_service_id: The carrier_service_id of this CarrierServiceSubService.  # noqa: E501
        :type: int
        """

        self._carrier_service_id = carrier_service_id

    @property
    def carrier_service(self):
        """Gets the carrier_service of this CarrierServiceSubService.  # noqa: E501


        :return: The carrier_service of this CarrierServiceSubService.  # noqa: E501
        :rtype: CarrierServiceLite
        """
        return self._carrier_service

    @carrier_service.setter
    def carrier_service(self, carrier_service):
        """Sets the carrier_service of this CarrierServiceSubService.


        :param carrier_service: The carrier_service of this CarrierServiceSubService.  # noqa: E501
        :type: CarrierServiceLite
        """

        self._carrier_service = carrier_service

    @property
    def sub_service_id(self):
        """Gets the sub_service_id of this CarrierServiceSubService.  # noqa: E501


        :return: The sub_service_id of this CarrierServiceSubService.  # noqa: E501
        :rtype: int
        """
        return self._sub_service_id

    @sub_service_id.setter
    def sub_service_id(self, sub_service_id):
        """Sets the sub_service_id of this CarrierServiceSubService.


        :param sub_service_id: The sub_service_id of this CarrierServiceSubService.  # noqa: E501
        :type: int
        """

        self._sub_service_id = sub_service_id

    @property
    def sub_service(self):
        """Gets the sub_service of this CarrierServiceSubService.  # noqa: E501


        :return: The sub_service of this CarrierServiceSubService.  # noqa: E501
        :rtype: SubService
        """
        return self._sub_service

    @sub_service.setter
    def sub_service(self, sub_service):
        """Sets the sub_service of this CarrierServiceSubService.


        :param sub_service: The sub_service of this CarrierServiceSubService.  # noqa: E501
        :type: SubService
        """

        self._sub_service = sub_service

    @property
    def is_default(self):
        """Gets the is_default of this CarrierServiceSubService.  # noqa: E501


        :return: The is_default of this CarrierServiceSubService.  # noqa: E501
        :rtype: bool
        """
        return self._is_default

    @is_default.setter
    def is_default(self, is_default):
        """Sets the is_default of this CarrierServiceSubService.


        :param is_default: The is_default of this CarrierServiceSubService.  # noqa: E501
        :type: bool
        """

        self._is_default = is_default

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CarrierServiceSubService, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CarrierServiceSubService):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
