# coding: utf-8

"""
    Machship API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CompanyCarrierAccountSellLaneRateBreakSet(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'breaks': 'list[CompanyCarrierAccountSellLaneRateBreak]',
        'break_count': 'int',
        'carrier_item_type': 'CarrierItemTypeLite'
    }

    attribute_map = {
        'breaks': 'breaks',
        'break_count': 'breakCount',
        'carrier_item_type': 'carrierItemType'
    }

    def __init__(self, breaks=None, break_count=None, carrier_item_type=None):  # noqa: E501
        """CompanyCarrierAccountSellLaneRateBreakSet - a model defined in Swagger"""  # noqa: E501
        self._breaks = None
        self._break_count = None
        self._carrier_item_type = None
        self.discriminator = None
        if breaks is not None:
            self.breaks = breaks
        if break_count is not None:
            self.break_count = break_count
        if carrier_item_type is not None:
            self.carrier_item_type = carrier_item_type

    @property
    def breaks(self):
        """Gets the breaks of this CompanyCarrierAccountSellLaneRateBreakSet.  # noqa: E501


        :return: The breaks of this CompanyCarrierAccountSellLaneRateBreakSet.  # noqa: E501
        :rtype: list[CompanyCarrierAccountSellLaneRateBreak]
        """
        return self._breaks

    @breaks.setter
    def breaks(self, breaks):
        """Sets the breaks of this CompanyCarrierAccountSellLaneRateBreakSet.


        :param breaks: The breaks of this CompanyCarrierAccountSellLaneRateBreakSet.  # noqa: E501
        :type: list[CompanyCarrierAccountSellLaneRateBreak]
        """

        self._breaks = breaks

    @property
    def break_count(self):
        """Gets the break_count of this CompanyCarrierAccountSellLaneRateBreakSet.  # noqa: E501


        :return: The break_count of this CompanyCarrierAccountSellLaneRateBreakSet.  # noqa: E501
        :rtype: int
        """
        return self._break_count

    @break_count.setter
    def break_count(self, break_count):
        """Sets the break_count of this CompanyCarrierAccountSellLaneRateBreakSet.


        :param break_count: The break_count of this CompanyCarrierAccountSellLaneRateBreakSet.  # noqa: E501
        :type: int
        """

        self._break_count = break_count

    @property
    def carrier_item_type(self):
        """Gets the carrier_item_type of this CompanyCarrierAccountSellLaneRateBreakSet.  # noqa: E501


        :return: The carrier_item_type of this CompanyCarrierAccountSellLaneRateBreakSet.  # noqa: E501
        :rtype: CarrierItemTypeLite
        """
        return self._carrier_item_type

    @carrier_item_type.setter
    def carrier_item_type(self, carrier_item_type):
        """Sets the carrier_item_type of this CompanyCarrierAccountSellLaneRateBreakSet.


        :param carrier_item_type: The carrier_item_type of this CompanyCarrierAccountSellLaneRateBreakSet.  # noqa: E501
        :type: CarrierItemTypeLite
        """

        self._carrier_item_type = carrier_item_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CompanyCarrierAccountSellLaneRateBreakSet, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompanyCarrierAccountSellLaneRateBreakSet):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
