# coding: utf-8

"""
    Machship API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrganisationInformation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'status': 'OrganisationStatus',
        'text_messaging_disabled': 'bool',
        'deactivated_mode': 'OrganisationDeactivatedMode'
    }

    attribute_map = {
        'id': 'id',
        'status': 'status',
        'text_messaging_disabled': 'textMessagingDisabled',
        'deactivated_mode': 'deactivatedMode'
    }

    def __init__(self, id=None, status=None, text_messaging_disabled=None, deactivated_mode=None):  # noqa: E501
        """OrganisationInformation - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._status = None
        self._text_messaging_disabled = None
        self._deactivated_mode = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if status is not None:
            self.status = status
        if text_messaging_disabled is not None:
            self.text_messaging_disabled = text_messaging_disabled
        if deactivated_mode is not None:
            self.deactivated_mode = deactivated_mode

    @property
    def id(self):
        """Gets the id of this OrganisationInformation.  # noqa: E501

        The ID of the organisation in the MachShip database  # noqa: E501

        :return: The id of this OrganisationInformation.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OrganisationInformation.

        The ID of the organisation in the MachShip database  # noqa: E501

        :param id: The id of this OrganisationInformation.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def status(self):
        """Gets the status of this OrganisationInformation.  # noqa: E501


        :return: The status of this OrganisationInformation.  # noqa: E501
        :rtype: OrganisationStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this OrganisationInformation.


        :param status: The status of this OrganisationInformation.  # noqa: E501
        :type: OrganisationStatus
        """

        self._status = status

    @property
    def text_messaging_disabled(self):
        """Gets the text_messaging_disabled of this OrganisationInformation.  # noqa: E501

        When true text messages will never be queued, even in the live system  # noqa: E501

        :return: The text_messaging_disabled of this OrganisationInformation.  # noqa: E501
        :rtype: bool
        """
        return self._text_messaging_disabled

    @text_messaging_disabled.setter
    def text_messaging_disabled(self, text_messaging_disabled):
        """Sets the text_messaging_disabled of this OrganisationInformation.

        When true text messages will never be queued, even in the live system  # noqa: E501

        :param text_messaging_disabled: The text_messaging_disabled of this OrganisationInformation.  # noqa: E501
        :type: bool
        """

        self._text_messaging_disabled = text_messaging_disabled

    @property
    def deactivated_mode(self):
        """Gets the deactivated_mode of this OrganisationInformation.  # noqa: E501


        :return: The deactivated_mode of this OrganisationInformation.  # noqa: E501
        :rtype: OrganisationDeactivatedMode
        """
        return self._deactivated_mode

    @deactivated_mode.setter
    def deactivated_mode(self, deactivated_mode):
        """Sets the deactivated_mode of this OrganisationInformation.


        :param deactivated_mode: The deactivated_mode of this OrganisationInformation.  # noqa: E501
        :type: OrganisationDeactivatedMode
        """

        self._deactivated_mode = deactivated_mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrganisationInformation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrganisationInformation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
