# coding: utf-8

"""
    Machship API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PermanentPickup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'carrier_id': 'int',
        'carrier': 'CarrierLite',
        'permanent_pickup_carrier_services': 'list[PermanentPickupCarrierService]'
    }

    attribute_map = {
        'id': 'id',
        'carrier_id': 'carrierId',
        'carrier': 'carrier',
        'permanent_pickup_carrier_services': 'permanentPickupCarrierServices'
    }

    def __init__(self, id=None, carrier_id=None, carrier=None, permanent_pickup_carrier_services=None):  # noqa: E501
        """PermanentPickup - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._carrier_id = None
        self._carrier = None
        self._permanent_pickup_carrier_services = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if carrier_id is not None:
            self.carrier_id = carrier_id
        if carrier is not None:
            self.carrier = carrier
        if permanent_pickup_carrier_services is not None:
            self.permanent_pickup_carrier_services = permanent_pickup_carrier_services

    @property
    def id(self):
        """Gets the id of this PermanentPickup.  # noqa: E501


        :return: The id of this PermanentPickup.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PermanentPickup.


        :param id: The id of this PermanentPickup.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def carrier_id(self):
        """Gets the carrier_id of this PermanentPickup.  # noqa: E501


        :return: The carrier_id of this PermanentPickup.  # noqa: E501
        :rtype: int
        """
        return self._carrier_id

    @carrier_id.setter
    def carrier_id(self, carrier_id):
        """Sets the carrier_id of this PermanentPickup.


        :param carrier_id: The carrier_id of this PermanentPickup.  # noqa: E501
        :type: int
        """

        self._carrier_id = carrier_id

    @property
    def carrier(self):
        """Gets the carrier of this PermanentPickup.  # noqa: E501


        :return: The carrier of this PermanentPickup.  # noqa: E501
        :rtype: CarrierLite
        """
        return self._carrier

    @carrier.setter
    def carrier(self, carrier):
        """Sets the carrier of this PermanentPickup.


        :param carrier: The carrier of this PermanentPickup.  # noqa: E501
        :type: CarrierLite
        """

        self._carrier = carrier

    @property
    def permanent_pickup_carrier_services(self):
        """Gets the permanent_pickup_carrier_services of this PermanentPickup.  # noqa: E501


        :return: The permanent_pickup_carrier_services of this PermanentPickup.  # noqa: E501
        :rtype: list[PermanentPickupCarrierService]
        """
        return self._permanent_pickup_carrier_services

    @permanent_pickup_carrier_services.setter
    def permanent_pickup_carrier_services(self, permanent_pickup_carrier_services):
        """Sets the permanent_pickup_carrier_services of this PermanentPickup.


        :param permanent_pickup_carrier_services: The permanent_pickup_carrier_services of this PermanentPickup.  # noqa: E501
        :type: list[PermanentPickupCarrierService]
        """

        self._permanent_pickup_carrier_services = permanent_pickup_carrier_services

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PermanentPickup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PermanentPickup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
