# coding: utf-8

"""
    Machship API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ReceiverAccount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'company_id': 'int',
        'company': 'CompanyLite',
        'carrier_id': 'int',
        'carrier': 'CarrierLite',
        'name': 'str',
        'account_code': 'str',
        'display_name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'company_id': 'companyId',
        'company': 'company',
        'carrier_id': 'carrierId',
        'carrier': 'carrier',
        'name': 'name',
        'account_code': 'accountCode',
        'display_name': 'displayName'
    }

    def __init__(self, id=None, company_id=None, company=None, carrier_id=None, carrier=None, name=None, account_code=None, display_name=None):  # noqa: E501
        """ReceiverAccount - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._company_id = None
        self._company = None
        self._carrier_id = None
        self._carrier = None
        self._name = None
        self._account_code = None
        self._display_name = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if company_id is not None:
            self.company_id = company_id
        if company is not None:
            self.company = company
        if carrier_id is not None:
            self.carrier_id = carrier_id
        if carrier is not None:
            self.carrier = carrier
        self.name = name
        self.account_code = account_code
        if display_name is not None:
            self.display_name = display_name

    @property
    def id(self):
        """Gets the id of this ReceiverAccount.  # noqa: E501


        :return: The id of this ReceiverAccount.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ReceiverAccount.


        :param id: The id of this ReceiverAccount.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def company_id(self):
        """Gets the company_id of this ReceiverAccount.  # noqa: E501


        :return: The company_id of this ReceiverAccount.  # noqa: E501
        :rtype: int
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id):
        """Sets the company_id of this ReceiverAccount.


        :param company_id: The company_id of this ReceiverAccount.  # noqa: E501
        :type: int
        """

        self._company_id = company_id

    @property
    def company(self):
        """Gets the company of this ReceiverAccount.  # noqa: E501


        :return: The company of this ReceiverAccount.  # noqa: E501
        :rtype: CompanyLite
        """
        return self._company

    @company.setter
    def company(self, company):
        """Sets the company of this ReceiverAccount.


        :param company: The company of this ReceiverAccount.  # noqa: E501
        :type: CompanyLite
        """

        self._company = company

    @property
    def carrier_id(self):
        """Gets the carrier_id of this ReceiverAccount.  # noqa: E501


        :return: The carrier_id of this ReceiverAccount.  # noqa: E501
        :rtype: int
        """
        return self._carrier_id

    @carrier_id.setter
    def carrier_id(self, carrier_id):
        """Sets the carrier_id of this ReceiverAccount.


        :param carrier_id: The carrier_id of this ReceiverAccount.  # noqa: E501
        :type: int
        """

        self._carrier_id = carrier_id

    @property
    def carrier(self):
        """Gets the carrier of this ReceiverAccount.  # noqa: E501


        :return: The carrier of this ReceiverAccount.  # noqa: E501
        :rtype: CarrierLite
        """
        return self._carrier

    @carrier.setter
    def carrier(self, carrier):
        """Sets the carrier of this ReceiverAccount.


        :param carrier: The carrier of this ReceiverAccount.  # noqa: E501
        :type: CarrierLite
        """

        self._carrier = carrier

    @property
    def name(self):
        """Gets the name of this ReceiverAccount.  # noqa: E501


        :return: The name of this ReceiverAccount.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ReceiverAccount.


        :param name: The name of this ReceiverAccount.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def account_code(self):
        """Gets the account_code of this ReceiverAccount.  # noqa: E501


        :return: The account_code of this ReceiverAccount.  # noqa: E501
        :rtype: str
        """
        return self._account_code

    @account_code.setter
    def account_code(self, account_code):
        """Sets the account_code of this ReceiverAccount.


        :param account_code: The account_code of this ReceiverAccount.  # noqa: E501
        :type: str
        """
        if account_code is None:
            raise ValueError("Invalid value for `account_code`, must not be `None`")  # noqa: E501

        self._account_code = account_code

    @property
    def display_name(self):
        """Gets the display_name of this ReceiverAccount.  # noqa: E501


        :return: The display_name of this ReceiverAccount.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this ReceiverAccount.


        :param display_name: The display_name of this ReceiverAccount.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReceiverAccount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReceiverAccount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
