# coding: utf-8

"""
    Machship API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SubService(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'carrier_id': 'int',
        'carrier': 'CarrierLite',
        'name': 'str',
        'abbreviation': 'str',
        'serialised_settings': 'str',
        'carrier_service_sub_services': 'list[CarrierServiceSubService]'
    }

    attribute_map = {
        'id': 'id',
        'carrier_id': 'carrierId',
        'carrier': 'carrier',
        'name': 'name',
        'abbreviation': 'abbreviation',
        'serialised_settings': 'serialisedSettings',
        'carrier_service_sub_services': 'carrierServiceSubServices'
    }

    def __init__(self, id=None, carrier_id=None, carrier=None, name=None, abbreviation=None, serialised_settings=None, carrier_service_sub_services=None):  # noqa: E501
        """SubService - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._carrier_id = None
        self._carrier = None
        self._name = None
        self._abbreviation = None
        self._serialised_settings = None
        self._carrier_service_sub_services = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if carrier_id is not None:
            self.carrier_id = carrier_id
        if carrier is not None:
            self.carrier = carrier
        if name is not None:
            self.name = name
        if abbreviation is not None:
            self.abbreviation = abbreviation
        if serialised_settings is not None:
            self.serialised_settings = serialised_settings
        if carrier_service_sub_services is not None:
            self.carrier_service_sub_services = carrier_service_sub_services

    @property
    def id(self):
        """Gets the id of this SubService.  # noqa: E501


        :return: The id of this SubService.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SubService.


        :param id: The id of this SubService.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def carrier_id(self):
        """Gets the carrier_id of this SubService.  # noqa: E501


        :return: The carrier_id of this SubService.  # noqa: E501
        :rtype: int
        """
        return self._carrier_id

    @carrier_id.setter
    def carrier_id(self, carrier_id):
        """Sets the carrier_id of this SubService.


        :param carrier_id: The carrier_id of this SubService.  # noqa: E501
        :type: int
        """

        self._carrier_id = carrier_id

    @property
    def carrier(self):
        """Gets the carrier of this SubService.  # noqa: E501


        :return: The carrier of this SubService.  # noqa: E501
        :rtype: CarrierLite
        """
        return self._carrier

    @carrier.setter
    def carrier(self, carrier):
        """Sets the carrier of this SubService.


        :param carrier: The carrier of this SubService.  # noqa: E501
        :type: CarrierLite
        """

        self._carrier = carrier

    @property
    def name(self):
        """Gets the name of this SubService.  # noqa: E501


        :return: The name of this SubService.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SubService.


        :param name: The name of this SubService.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def abbreviation(self):
        """Gets the abbreviation of this SubService.  # noqa: E501


        :return: The abbreviation of this SubService.  # noqa: E501
        :rtype: str
        """
        return self._abbreviation

    @abbreviation.setter
    def abbreviation(self, abbreviation):
        """Sets the abbreviation of this SubService.


        :param abbreviation: The abbreviation of this SubService.  # noqa: E501
        :type: str
        """

        self._abbreviation = abbreviation

    @property
    def serialised_settings(self):
        """Gets the serialised_settings of this SubService.  # noqa: E501


        :return: The serialised_settings of this SubService.  # noqa: E501
        :rtype: str
        """
        return self._serialised_settings

    @serialised_settings.setter
    def serialised_settings(self, serialised_settings):
        """Sets the serialised_settings of this SubService.


        :param serialised_settings: The serialised_settings of this SubService.  # noqa: E501
        :type: str
        """

        self._serialised_settings = serialised_settings

    @property
    def carrier_service_sub_services(self):
        """Gets the carrier_service_sub_services of this SubService.  # noqa: E501


        :return: The carrier_service_sub_services of this SubService.  # noqa: E501
        :rtype: list[CarrierServiceSubService]
        """
        return self._carrier_service_sub_services

    @carrier_service_sub_services.setter
    def carrier_service_sub_services(self, carrier_service_sub_services):
        """Sets the carrier_service_sub_services of this SubService.


        :param carrier_service_sub_services: The carrier_service_sub_services of this SubService.  # noqa: E501
        :type: list[CarrierServiceSubService]
        """

        self._carrier_service_sub_services = carrier_service_sub_services

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubService, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubService):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
